---
swagger: "2.0"
info:
  version: "2017-01-16T12:28:44Z"
  title: Hipchat Burndown
  description: Extension that send the Jira burndown chart to a hipchat room
schemes:
- "https"
paths:
  /install:
    get:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        200:
          description: "200 response"
      description: Returns the hipchat integration descriptor
      x-amazon-lambda-name: HipchatBurndown
      x-amazon-lambda-handler: lambda.handler
      x-amazon-lambda-runtime: nodejs4.3
      x-amazon-lambda-timeout: 60
      x-amazon-apigateway-integration:
        type: aws_proxy
        httpMethod: POST
        passthroughBehavior: when_no_match
  /burndown:
    post:
      produces:
      - "application/json"
      responses:
        200:
          description: "200 response"
      x-amazon-lambda-name: HipchatBurndown
      x-amazon-apigateway-integration:
        type: aws_proxy
        httpMethod: POST
        passthroughBehavior: when_no_match
  /register:
    post:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        200:
          description: "200 response"
      x-amazon-lambda-name: HipchatBurndown
      x-amazon-apigateway-integration:
        type: aws_proxy
        httpMethod: POST
        passthroughBehavior: when_no_match
  /installed:
    post:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        200:
          description: "200 response"
      x-amazon-lambda-name: HipchatBurndown
      x-amazon-apigateway-integration:
        type: aws_proxy
        httpMethod: POST
        passthroughBehavior: when_no_match
  /burndown/{id}/{version}/image.png:
    get:
      parameters:
      - name: id
        in: path
        description: The ID of the resource
        type: string
        required: true
      - name: version
        in: path
        description: The ID of the resource
        type: string
        required: true
      responses:
        301:
          description: "301 response"
      x-amazon-lambda-name: HipchatBurndown
      x-amazon-apigateway-integration:
        type: aws_proxy
        httpMethod: POST
        passthroughBehavior: when_no_match
  /burndown/{id}/{version}/thumbnail.png:
    get:
      parameters:
      - name: id
        in: path
        description: The ID of the resource
        type: string
        required: true
      - name: version
        in: path
        description: The ID of the resource
        type: string
        required: true
      responses:
        301:
          description: "301 response"
      x-amazon-lambda-name: HipchatBurndown
      x-amazon-apigateway-integration:
        type: aws_proxy
        httpMethod: POST
        passthroughBehavior: when_no_match